gripper_motor:
  ID: 1
  Baud_Rate: 1
  Return_Delay_Time: 250
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 1023
  Status_Return_Level: 2
  Alarm_LED: 36
  Shutdown: 36